name: 'Jest Action'
description: 'Run jest and report the results inline'
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  jest-bin:
    required: true
    description: 'Path to your jest library, probably node_modules/.bin/jest'
  custom-working-directory:
    required: false
    description: 'Path to your working directory, uses `.` if not provided'
  check-run-subtitle:
    required: false
    description: 'A subtitle to add to the check run when annotations are passed back to avoid overwriting each other'
  find-related-tests:
    required: false
    description: 'Set to 1 to make it so that only related test files are run, not all tests.'
  run-all-if-changed:
    required: false
    description: 'Comma-separated list of files which, if changed, trigger a re-check of all files, ignoring find-related-tests. Directories can be specified with a trailing /, in which case all descendents of that directory would trigger a full re-check.'
branding:
  icon: check-circle
  color: red
